### ISSUE TITLE
Error after running test 

### ISSUE THREAD

**Issue by karimelhou** [riad-azz/flask-template#2]
(venvT) karim@Karims-MacBook-Pro flask-template % python3 -m pytest
========================================================= test session starts =========================================================
platform darwin -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/karim/Documents/MASTER M2/ML/flask-template
collected 10 items                                                                                                                    

tests/flask/test_api.py ..F....                                                                                                 [ 70%]
tests/flask/test_cache.py F                                                                                                     [ 80%]
tests/flask/test_cors.py .                                                                                                      [ 90%]
tests/flask/test_ratelimiter.py E                                                                                               [100%]

=============================================================== ERRORS ================================================================
_________________________________________________ ERROR at setup of test_rate_limiter _________________________________________________

    @pytest.fixture
    def app():
        app = create_app()
    
        limiter.enabled = True
>       limiter.reset()

tests/flask/test_ratelimiter.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venvT/lib/python3.10/site-packages/flask_limiter/extension.py:805: in reset
    self.storage.reset()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <flask_limiter.extension.Limiter object at 0x105b99ff0>

    @property
    def storage(self) -> Storage:
        """
        The backend storage configured for the rate limiter
        """
>       assert self._storage
E       AssertionError

venvT/lib/python3.10/site-packages/flask_limiter/extension.py:815: AssertionError
============================================================== FAILURES ===============================================================
_________________________________________________________ test_api_ratelimit __________________________________________________________

app = <Flask 'app'>

    def test_api_ratelimit(app):
        with app.test_client() as client:
            success_response = client.get("/api/tests/ratelimit")
            limited_response = client.get("/api/tests/ratelimit")
    
        assert success_response.status_code == 200
        assert success_response.json["status"] == "success"
        assert success_response.json["data"]["title"] == "riad-azz"
        assert success_response.json["data"]["content"] == "Rate limit API response"
    
>       assert limited_response.status_code == 429
E       assert 200 == 429
E        +  where 200 = <WrapperTestResponse streamed [200 OK]>.status_code

tests/flask/test_api.py:41: AssertionError
___________________________________________________________ test_api_cache ____________________________________________________________

app = <Flask 'app'>

    def test_api_cache(app):
        request_url = "/api/tests/cached"
        with app.test_client() as client:
            response = client.get(request_url)
            assert response.status_code == 200
            assert response.headers.get("Is-Cached-Response") is None
            assert response.json["status"] == "success"
            assert response.json["data"]["title"] == "riad-azz"
            assert response.json["data"]["content"] == "Cached API response"
    
        request = response.request
        is_cached = get_cached_response(request)
    
>       assert bool(is_cached) is True
E       assert False is True
E        +  where False = bool(None)

tests/flask/test_cache.py:29: AssertionError
======================================================= short test summary info =======================================================
FAILED tests/flask/test_api.py::test_api_ratelimit - assert 200 == 429
FAILED tests/flask/test_cache.py::test_api_cache - assert False is True
ERROR tests/flask/test_ratelimiter.py::test_rate_limiter - AssertionError
================================================ 2 failed, 7 passed, 1 error in 1.46s =================================================
(venvT) karim@Karims-MacBook-Pro flask-template %

**Comment by riad-azz** [comment]
I just ran the tests and it seems to run with no problems. Make sure to create the `.env.dev ` and `.env` files and fill them accordingly like the `.env.example` because that's how you enable the cache and rate limit features.

```.env
# Flask Variables
SECRET_KEY="YOUR-SECRET-KEY"
# Flask Ratelimit
RATELIMIT_ENABLED="True"
RATELIMIT_STORAGE_URI="memory://" # or redis://localhost:6379/0
# Flask Cache
CACHE_ENABLED="True"
CACHE_TYPE="SimpleCache" # or RedisCache
CACHE_STORAGE_URL="YOUR-REDIS-URL" # Required only for CACHE_TYPE RedisCache
```

I have updated the `README.md` you can check it out for more info.
